swagger: "2.0"
info:
  version: "0.0.1"
  title: DocStack Notifications API
# during dev, should point to your local machine
host: localhost:8999
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /subscriptions/{topic}:
    x-swagger-router-controller: subscriptions
    get:
      description: Gets a list of subscriptions per specified topic
      operationId: getSubscriptionsByTopic
      parameters:
        - name: topic
          in: path
          description: topic to fetch subscriptions for
          required: true
          type: string
      responses:
        200: 
          description: OK
          schema: 
            $ref: '#/definitions/SubscriptionList'
  /subscription:
    x-swagger-router-controller: subscriptions
    post:
      description: Creates a subscription
      operationId: addSubscription
      parameters:
        - name: subscription
          in: body
          description: new subscription
          required: true
          schema:
            $ref: '#/definitions/Subscription'
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/NewSubscriptionResponse'
        400:
          description: Invalid request
        default:
          description: An error has occurred
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  SubscriptionList:
    type: array
    items: 
      $ref: '#/definitions/Subscription'
  Subscription:
    type: object
    properties:
      topic:
        type: string
      url:
        type: string
      argument:
        type: string
    required:
      - topic
      - url
      - argument
  NewSubscriptionResponse:
    type: object
    properties:
      message:
        type: string
