swagger: "2.0"
info:
  version: "0.0.1"
  title: docStack Notifications API
# during dev, should point to your local machine
host: localhost:8999
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /notification:
    x-swagger-router-controller: notifications
    post:
      description: Receives a notification
      operationId: notification
      parameters:
        - name: notification
          in: body
          description: new notif
          schema:
            $ref: '#/definitions/NewNotification'
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/NewNotificationResponse'
        default:
          description: Bad request
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  NewNotification:
    type: object
    properties:
      client:
        type: string
  NewNotificationResponse:
    type: object
    properties:
      message:
        type: string
